name: SwiftUILab
settings:
  base:
    ALWAYS_SEARCH_USER_PATHS: NO
    COPY_PHASE_STRIP: NO
  configs:
    debug:
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      DEBUG_INFORMATION_FORMAT: dwarf
    release:
      SWIFT_OPTIMIZATION_LEVEL: -O
      SWIFT_COMPILATION_MODE: wholemodule
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
options:
  settingPresets: none
  bundleIdPrefix: com.masahikokobayashi
configFiles:
  Debug: Configs/Debug.xcconfig
  Release: Configs/Release.xcconfig
schemes:
  SwiftUILab:
    build:
      targets:
        SwiftUILab: all
targets:
  SwiftUILab:
    type: application
    platform: iOS
    supportedDestinations: [iOS]
    deploymentTarget: 17.5
    sources: [SwiftUILab]
    configFiles:
      Debug: Configs/SwiftUILab-Debug.xcconfig
      Release: Configs/SwiftUILab-Release.xcconfig
    settings:
      base:
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
        TARGETED_DEVICE_FAMILY: 1
        SWIFT_VERSION: 6.1
        DEVELOPMENT_TEAM: TENQMTMR26
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_NAME: $(TARGET_NAME)
  SwiftUILabTests:
    type: bundle.unit-test
    platform: iOS
    sources: [SwiftUILabTests]
    dependencies:
      - target: SwiftUILab
    settings:
      base:
        SWIFT_VERSION: 6.1
        TARGETED_DEVICE_FAMILY: 1
  SwiftUILabUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [SwiftUILabUITests]
    dependencies:
      - target: SwiftUILab
    settings:
      base:
        SWIFT_VERSION: 6.1
        TARGETED_DEVICE_FAMILY: 1
